import "./globals.scss";
import { Poppins } from "next/font/google";
import { ReactNode } from "react";
import { Metadata } from "next";
import Script from "next/script";
import LocalConfig from "@/constants/config";
import { WebVitals } from "@/components/common/WebVitals";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin", "latin-ext"],
  display: "swap",
  preload: true,
  fallback: [
    "system-ui",
    "arial",
    "BlinkMacSystemFont",
    "Segoe UI",
    "Roboto",
    "Oxygen",
    "Ubuntu",
    "Fira Sans",
    "Droid Sans",
  ],
});

export const metadata: Metadata = {
  title: "Gajraj Singh Bhati",
  description:
    "Gajraj Singh Bhati is a Software Engineer and Full Stack Developer from India, skilled in front-end and back-end development using modern tech stacks.",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: [
    {
      url: "/favicon.ico",
      rel: "icon",
      sizes: "any",
      type: "image/svg+xml",
    },
  ],
  keywords: [
    "gajraj",
    "gajraj rtu kota",
    "gajraj bhati",
    "gajraj reactjs",
    "gajraj nodejs",
    "gajraj singh",
    "gajraj singh bhati",
    "gajraj singh rtu kota",
    "developer gajraj singh bhati",
    "MERN stack developer",
    "gajraj singh github",
    "gajraj singh linkedin",
    "engineer gajraj singh",
    "coder gajraj singh",
    "gajraj singh bhati portfolio",
    " gajraj singh bhati website",
    " gajraj singh bhati blog",
    " gajraj singh bhati resume",
    " gajraj singh bhati projects",
    " gajraj singh bhati contact",
    " gajraj singh bhati about",
    " gajraj singh bhati skills",
    " gajraj singh bhati experience",
    " gajraj singh bhati education",
    " gajraj singh bhati work",
    " gajraj singh bhati tech",
    " gajraj singh bhati tech stack",
    " gajraj singh bhati full stack developer",
    " gajraj singh bhati software engineer",
    " gajraj singh bhati web developer",
    " gajraj singh bhati front-end developer",
    " gajraj singh bhati back-end developer",
    " gajraj singh bhati mobile developer",
    " gajraj singh bhati android developer",
    " gajraj singh bhati ios developer",
    " gajraj singh bhati react developer",
    " gajraj singh bhati react native developer",
    " gajraj singh bhati node developer",
    " gajraj singh bhati github",
    " gajraj singh bhati linkedin",
    " gajraj singh bhati twitter",
    " gajraj singh bhati facebook",
    " gajraj singh bhati instagram",
    " software developer",
    " software engineer",
    " full stack developer",
    " MERN stack ",
    " product development",
    "gajraj",
    "gajraj singh ",
    "gajraj bhati",
    "gajraj software",
    "gajraj developer",
    "gajraj engineer",
    "gajraj portfolio",
    "gajraj website",
    "gajraj blog",
    "gajraj resume",
    "gajraj projects",
    "gajraj contact",
    "gajraj about",
    "gajraj skills",
    "gajraj experience",
    "gajraj education",
    "gajraj work",
    "gajraj tech",
    "gajraj tech stack",
    "gajraj full stack developer",
    "gajraj software engineer",
    "gajraj web developer",
    "gajraj front-end developer",
    "gajraj back-end developer",
    "gajraj mobile developer",
    "gajraj android developer",
    "gajraj ios developer",
    "gajraj react developer",
    "gajraj react native developer",
    "gajraj node developer",
    "gajraj github",
    "gajraj linkedin",
    "gajraj twitter",
    "gajraj facebook",
    "gajraj instagram",
    "gajraj software developer",
    "gajraj software engineer",
    "gajraj full stack developer",
    "gajraj MERN stack ",
    "gajraj product development",
    "gajraj software",
    "gajraj developer",
    "gajraj engineer",
    "gajraj portfolio",
    "gajraj website",
    "gajraj singh",
    "gajraj singh engineer",
    "gajraj singh developer",
    "gajraj singh software",
    "gajraj singh portfolio",
    "gajraj singh website",
    "gajraj singh blog",
    "gajraj singh resume",
    "gajraj singh projects",
    "gajraj singh contact",
    "gajraj singh about",
    "gajraj singh skills",
    "gajraj singh experience",
    "gajraj singh education",
    "gajraj singh work",
    "gajraj singh tech",
    "gajraj singh tech stack",
    "gajraj singh full stack developer",
    "gajraj singh software engineer",
    "gajraj singh web developer",
    "gajraj singh front-end developer",
    "gajraj singh back-end developer",
    "gajraj singh mobile developer",
    "gajraj singh android developer",
    "gajraj singh ios developer",
    "gajraj singh react developer",

    "gajraj singh react native developer",
    "gajraj singh node developer",
    "gajraj singh github",
    "gajraj singh linkedin",
    "gajraj singh twitter",
    "gajraj singh facebook",
    "gajraj singh instagram",
    "gajraj singh software developer",
    "gajraj singh software engineer",
    "gajraj singh full stack developer",
    "gajraj singh MERN stack ",
    "gajraj singh product development",
    "gajraj singh software",
    "gajraj singh developer",
    "gajraj singh engineer",
    "gajraj singh portfolio",
    "gajraj singh website",
    "gajraj singh blog",
    "gajraj singh resume",
    "gajraj singh projects",

    "gajraj singh contact",
    "gajraj singh about",
    "gajraj singh skills",
    "gajraj singh experience",
    "gajraj singh education",
    "gajraj singh work",
    "gajraj singh tech",
    "gajraj singh tech stack",
    "gajraj singh full stack developer",
    "gajraj singh software engineer",
    
    "gsbgajraj",
    "gajraj-singh",
    "bhati gajraj",
    "full stack developer",
    "indian developer",
    "gsbgajraj github",
    "best software engineer in Kota",
    "best software engineer in Rajasthan",
    "best software engineer in India",
    "best full stack developer in Kota",
    "best full stack developer in Rajasthan",
    "MERN stack developer in jaipur",
    "software developer in jaipur",
    "software developer in Kota",
    "software developer in Rajasthan",
    "software developer in India",
    "full stack developer in jaipur",
    "full stack developer in Kota",
    "full stack developer in Rajasthan",
    "best software developer in kota",
    "web developer in india",
    "web developer in jaipur",
    "web developer in Kota",
    "web developer in Rajasthan",
    "software  engineer in japur",
    "software  engineer in Kota",
    "software  engineer in Rajasthan,",
    "software  engineer in India",
    "best web developer in kota",
    "website development in kota",
    "website developer in Jaipur",
    "hire remote software developer in india",
    "hire remote software developer in kota",
    "website development services in india",
    "web developer near me",
        "top full stack developer in Kota",  
    "top full stack developer in Rajasthan",  
    "best MERN stack developer in Jaipur",  
    "experienced software developer in Jaipur",  
    "freelance software developer in Kota",  
    "hire best software developer in Rajasthan",  
    "top-rated software developer in India",  
    "expert full stack developer in Jaipur",  
    "top full stack developer in Kota",  
    "skilled full stack developer in Rajasthan",  
    "award-winning software developer in Kota",  
    "professional web developer in India",  
    "affordable web developer in Jaipur",  
    "freelance web developer in Kota",  
    "website development company in Rajasthan",  
    "experienced software engineer in Jaipur",  
    "certified software engineer in Kota",  
    "best software engineer in Rajasthan",  
    "leading software engineer in India",  
    "top-rated web developer in Kota",  
    "custom website development in Kota",  
    "best website developer in Jaipur",  
    "hire top remote software developer in India",  
    "remote software developer for hire in Kota",  
    "best website development services in India",  
    "affordable website development in Rajasthan",  
    "custom software solutions in Jaipur",  
    "full stack web developer for hire in India",  
    "freelance MERN stack developer in Rajasthan",  
    "website design and development in Jaipur",
    "best software software engineer in kota",
    "Hire software engineer in kota",
    "Hire software developer in kota",
    "best software developer in kota from rtu kota",
    "best software developer in kota rajasthan from rajasthan technical university kota",
    "best website developer in kota rajasthan from rajasthan technical university kota",
    "best software developer in kota from engineering college kota",    
    "best engineer in kota from engineering college kota",   
    "top 10 software engineer in kota rajasthan", 
    "top 10 software engineer in rajasthan", 
    "top 10 software engineer in india", 
    "top 10 software engineer in the world", 
    "need website engineer to develop my website", 
  ],
};

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
  return (
    <html lang="en" className={poppins.className}>
      <head>
        <Script
          strategy="afterInteractive"
          src={`https://www.googletagmanager.com/gtag/js?id=${LocalConfig.values.NEXT_PUBLIC_GTAG_ID}`}
        />

        <Script id="google-analytics" strategy="afterInteractive">
          {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', '${LocalConfig.values.NEXT_PUBLIC_GTAG_ID}', {
            page_path: window.location.pathname,
          });
        `}
        </Script>
      </head>

      <body
        className={
          process.env.NODE_ENV === "development" ? "debug-screens" : ""
        }
      >
        {process.env.NODE_ENV === "development" ? <WebVitals /> : null}
        <main>{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
